### ISSUE TITLE
El ejemplo no compila en Visual Studio Community 2019RC 

### ISSUE THREAD

**Issue by SrDobrais** [dotnet/docs.es-es#120]
Aunque si compila en Visual Studio Community 2017

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 4343ac18-37c1-9a3e-0210-b69bf924db91
* Version Independent ID: 19d63151-4d8a-30c6-35de-0c8c277cde25
* Content: [Clases: Guía de programación de C#](https://docs.microsoft.com/es-es/dotnet/csharp/programming-guide/classes-and-structs/classes)
* Content Source: [docs/csharp/programming-guide/classes-and-structs/classes.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/programming-guide/classes-and-structs/classes.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11607](https://github.com/dotnet/docs/issues/11607) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @SrDobrais 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/11607
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
