### ISSUE TITLE
El Ejemplo no compila en Visual Studio Community 2019RC

### ISSUE THREAD

**Issue by SrDobrais** [dotnet/docs.es-es#121]
Aunque si compila en Visual Studio Community 2017

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a86f6ff1-21bf-44ad-f603-e311648929a4
* Version Independent ID: 9b08428b-beba-0f94-6635-73e26d0de446
* Content: [Palabra clave class: Referencia de C#](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/class)
* Content Source: [docs/csharp/language-reference/keywords/class.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/language-reference/keywords/class.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11608](https://github.com/dotnet/docs/issues/11608) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @SrDobrais 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/11608https://github.com/dotnet/docs/issues/11608
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
