### ISSUE TITLE
Sugerencia sobre el uso de TRIM

### ISSUE THREAD

**Issue by onieto07** [dotnet/docs.es-es#125]
En el ejemplo de uso de TRIM, se debería poner un punto al final de las oraciones para que se pueda visualizar bien el efecto de las diferentes sintaxis de TRIM, retomando el ejemplo mostrado podemos poner:

string greeting = "      Hello World!       ";
Console.WriteLine($"[{greeting}].");

string trimmedGreeting = greeting.TrimStart();
Console.WriteLine($"[{trimmedGreeting}].");

trimmedGreeting = greeting.TrimEnd();
Console.WriteLine($"[{trimmedGreeting}].");

trimmedGreeting = greeting.Trim();
Console.WriteLine($"[{trimmedGreeting}].");

Con este punto podemos ver el efecto de las diferentes variantes de trim sobre la cadena al ver desplazarse el punto final en la pantalla.

Saludos,

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 3d841900-8699-af9b-f879-c5cf9b54f21e
* Version Independent ID: 2d85eae9-01e1-17af-b282-715ec3dc0dcb
* Content: [Hola mundo: tutorial interactivo de introducción a C#](https://docs.microsoft.com/es-es/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/hello-world.yml](https://github.com/dotnet/docs.es-es/blob/live-sxs/docs/csharp/tutorials/intro-to-csharp/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11987](https://github.com/dotnet/docs/issues/11987) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @onieto07 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/11987

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
