### ISSUE TITLE
Índices y rangos

### ISSUE THREAD

**Issue by smaugcoath** [dotnet/docs.es-es#126]
Creo que hay un error en la descripción del operador ^ de los índices.
Se dice expresamente que "Los valores predeterminados son 0 para el índice de inicio y ^0 para el índice de final." Es decir, entiendo que para acceder a la última posición de un array se podría hacer con "array[^0]", que sería igual que array.Last();.

Sin embargo después los ejemplos tratan el último elemento como ^1. 

Tengo entendido que el último elemento viene definido por la posición ^1, según he leído en blogs externos, aunque aún no lo he probado.

Un saludo.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a94537c5-754e-9dea-94a8-7573011f588c
* Version Independent ID: aba09118-22c5-2c6a-954a-b9659a9644ae
* Content: [Novedades de C# 8.0: Guía de C#](https://docs.microsoft.com/es-es/dotnet/csharp/whats-new/csharp-8#feedback)
* Content Source: [docs/csharp/whats-new/csharp-8.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/whats-new/csharp-8.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11988](https://github.com/dotnet/docs/issues/11988) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @smaugcoath 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/11988
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
