### ISSUE TITLE
mlContext.Regression.Trainers.FastTree() Not Found

### ISSUE THREAD

**Issue by FoyCR** [dotnet/docs.es-es#129]
Si al ejecutar el tutorial no encuentran el algoritmo FastTree es por que en la versión 1.0 del ML .Net esto quedó en otro paquete NuGet por lo que simplemente es buscar en instalar el paquete Microsoft.ML.FastTree

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a30b3ff5-b5e6-ff02-6f60-b5cef6f34666
* Version Independent ID: fdf962e2-620e-d9ad-5057-5f96f52dc60f
* Content: [Tutorial: Predicción de precios mediante regresión - ML.NET](https://docs.microsoft.com/es-es/dotnet/machine-learning/tutorials/predict-prices#feedback)
* Content Source: [docs/machine-learning/tutorials/predict-prices.md](https://github.com/dotnet/docs.es-es/blob/live/docs/machine-learning/tutorials/predict-prices.md)
* Product: **dotnet-ml**
* GitHub Login: @JRAlexander
* Microsoft Alias: **johalex**

**Comment by CeciAc** [comment]
Hola, @FoyCR 

Valoramos enormemente su comentario y estamos haciendo todo lo posible por mejorar su experiencia en docs.microsoft.com. No obstante, necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by FoyCR** [comment]
Es solo un recordatorio de que al igual que se instala Microsoft.ML también
se debe instalar el paquete Microsoft.ML.FastTree
___________________________

Foy.
http://foyland.blogspot.com/
___________________________

**Comment by CeciAc** [comment]
Hola, @FoyCR 

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
