### ISSUE TITLE
Aclaración

### ISSUE THREAD

**Issue by pfebolo** [dotnet/docs.es-es#130]
donde dice: _se da cuenta de que las letras_
debería decir: _se da cuenta de que las **cartas**_

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 3befff27-c4fc-a699-90b3-903ce60234af
* Version Independent ID: 71ff10df-c0b0-9497-e448-82388ef1b1a1
* Content: [¿Qué es Docker?](https://docs.microsoft.com/es-es/dotnet/standard/microservices-architecture/container-docker-introduction/docker-defined#feedback)
* Content Source: [docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md](https://github.com/dotnet/docs.es-es/blob/live/docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by CeciAc** [comment]
Hola, @pfebolo 

Gracias por sus comentarios. 

Los revisaremos y nos pondremos en contacto con usted lo antes posible. 

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by CeciAc** [comment]
Hola, @pfebolo 

Gracias por sus comentarios. 

El equipo lingüístico ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-es/dotnet/standard/microservices-architecture/container-docker-introduction/docker-defined

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 
Equipo internacional de Microsoft Docs
