### ISSUE TITLE
"agregar" traducida sin necesidad y lleva a error

### ISSUE THREAD

**Issue by jmalarcon** [dotnet/docs.es-es#131]
La [palabra clave contextual](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/#contextual-keywords)`agregar` se ha traducido, pero no debería haberse hecho y debería haberse dejado `add` pues es el término utilizado por el lenguaje y por tanto no debe traducirse.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: fa5712fd-a965-e2a9-5b1c-0b295d5e8ccd
* Version Independent ID: 4b943400-309d-0437-5513-0533456297f0
* Content: [Palabras clave de C#](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/)
* Content Source: [docs/csharp/language-reference/keywords/index.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/language-reference/keywords/index.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hola, @

Gracias por sus comentarios. 

Los revisaremos y nos pondremos en contacto con usted lo antes posible. 

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by CeciAc** [comment]
Hola, @jmalarcon

Gracias por sus comentarios. 

El equipo lingüístico ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 
Equipo internacional de Microsoft Docs
