### ISSUE TITLE
No se comprueba correctamente el valor NULL en el Tutorial.

### ISSUE THREAD

**Issue by lacostaplans** [dotnet/docs.es-es#136]
La implementación, según la documenación, del metodo Answer (en SurveyResponse):

`        public string Answer(int index) => surveyResponses.GetValueOrDefault(index, "No answer")!;
`

Genera un warning CS8604.

La implementación correcta seria (para no tener el warning):

`   public string Answer(int index) => surveyResponses?.GetValueOrDefault(index, "No answer")!;
`

Pero con esta implementación, el siguiente código:

```
 var surveyResponse = new SurveyResponse(1);

string awswer = surveyResponse.Answer(1);

var length = answer.Length;

```

No genera aviso, pero al ejecutar, se inicial una **NullReferenceException** en la linea:

`var length = answer.Length;
`

Ya que **answer** es NULL. Sin embargo la firma del médodo es **public string Answer**, no **public string? Answer**.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b991cba9-efd4-68ae-283a-b575054b4907
* Version Independent ID: 793f790b-e2aa-e292-b12b-f4ba9763f172
* Content: [Diseño con tipos de referencia que aceptan valores NULL](https://docs.microsoft.com/es-es/dotnet/csharp/tutorials/nullable-reference-types)
* Content Source: [docs/csharp/tutorials/nullable-reference-types.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/tutorials/nullable-reference-types.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @lacostaplans
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #14542](https://github.com/dotnet/docs/issues/14542) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @lacostaplans

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/14542
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
