### ISSUE TITLE
En Español (España) version de Framework no coincide con el código adjunto

### ISSUE THREAD

**Issue by fedehaust** [dotnet/docs.es-es#137]
En
"La etiqueta TargetFramework especifica la implementación .NET a la que nos dirigimos. En un escenario avanzado, con una sola operación puede especificar varios marcos de destino y compilar en todos ellos. En este tutorial, nos centraremos en compilar únicamente para .NET Core 2.1."

Debería ser 
"La etiqueta TargetFramework especifica la implementación .NET a la que nos dirigimos. En un escenario avanzado, con una sola operación puede especificar varios marcos de destino y compilar en todos ellos. En este tutorial, nos centraremos en compilar únicamente para .NET Core 2.2."

En
"Después, definimos un espacio de nombres denominado Hello. Puede cambiar esto por cualquier cosa que desee. Se define una clase denominada Program dentro del espacio de nombres, con un método Main que toma una matriz de cadenas como argumento. Esta matriz contiene la lista de argumentos que se ha pasado cuando se llama al programa compilado. Tal y como está, esta matriz no se usa: todo lo que hace el programa es escribir "¡Hola a todos!" en la consola. Después, realizaremos cambios en el código que usará este argumento."

Debería ser
"Después, definimos un espacio de nombres denominado Hello. Puede cambiar esto por cualquier cosa que desee. Se define una clase denominada Program dentro del espacio de nombres, con un método Main que toma una matriz de cadenas como argumento. Esta matriz contiene la lista de argumentos que se ha pasado cuando se llama al programa compilado. Tal y como está, esta matriz no se usa: todo lo que hace el programa es escribir "Hello World!" en la consola. Después, realizaremos cambios en el código que usará este argumento."

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 9fa0c79e-1729-15f7-52e4-0c9afff43ec9
* Version Independent ID: 1c3c5d30-9690-8c4a-4e2c-2ce5f4386898
* Content: [Introducción a .NET Core con la CLI - .NET Core](https://docs.microsoft.com/es-es/dotnet/core/tutorials/using-with-xplat-cli#feedback)
* Content Source: [docs/core/tutorials/using-with-xplat-cli.md](https://github.com/dotnet/docs.es-es/blob/live/docs/core/tutorials/using-with-xplat-cli.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @fedehaust
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @fedehaust 

Gracias por sus comentarios. 

El equipo lingüístico ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-es/dotnet/core/tutorials/using-with-xplat-cli#feedback

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 
Equipo internacional de Microsoft Docs
