### ISSUE TITLE
Link del Libro en Español?

### ISSUE THREAD

**Issue by portal7** [dotnet/docs.es-es#142]
recuerdo que hubo una version en Español, hay posibilidad?. Gracias!!

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 031b20ec-7583-8277-f7a6-69ff3beffeac
* Version Independent ID: 58c0d74e-2a5d-297e-4770-e8e44878b683
* Content: [Microservicios de .NET. Arquitectura para aplicaciones .NET en contenedor](https://docs.microsoft.com/es-es/dotnet/architecture/microservices/#feedback)
* Content Source: [docs/architecture/microservices/index.md](https://github.com/dotnet/docs.es-es/blob/live/docs/architecture/microservices/index.md)
* Product: **dotnet-architecture**
* Technology: **microservices**
* GitHub Login: @nishanil
* Microsoft Alias: **nanil**

**Comment by srvbpigh** [comment]
Hello, @portal7
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard 
the contributor is asking for the es-es book link
can you help us here?
thanks in advance

**Comment by JasonCard** [comment]
Hi @portal7, @CeciAc, 
I am looking into this and will get back to you.

**Comment by portal7** [comment]
Fine!!

**Comment by JasonCard** [comment]
Hi @portal7, 
Thank you for your feedback.
You can now download PDF by clicking on this link below the Table of Contents:
![DownloadPDF](https://user-images.githubusercontent.com/18313964/67442998-e0274100-f5b7-11e9-8e85-80ad0dc748ac.png)
Please let me know if you have any further questions.
Kind regards,
Microsoft DOCS International Team
cc @CeciAc

**Comment by portal7** [comment]
Sorry but what i want is the link for the ebook on spanish language
When click on the EPUB | MOBI | PDF section  on https://docs.microsoft.com/es-es/dotnet/architecture/microservices/  links leads me to English Version of the ebook. 

Thanks in advance!

**Comment by JasonCard** [comment]
Hi @portal7, 
We are sorry, but those eBook formats are only available in English. 
So only the PDF that is automatically generated is available to download for localized languages. 
We are sorry for this inconvenience and thank you for your understanding. 
Kind regards,
Microsoft DOCS International Team
