### ISSUE TITLE
Error en el código mostrado de ejemplo

### ISSUE THREAD

**Issue by JKValero** [dotnet/docs.es-es#144]
Hay errores de declaración de variables en el código que se muestra como ejemplo, y que ante un programador sin mucha experiencia, puede acarrearle algunos problemas. Estoy trabajando son Option 
 Strict = On y se declaran 8 errores.
Saludos.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 5b4f461d-abc2-566a-3ba2-ba410acd4511
* Version Independent ID: 9e64496c-8561-8622-92dd-36b1d02c93c1
* Content: [Procedimiento Buscar archivos duplicados en un árbol de directorios (LINQ) (Visual Basic)](https://docs.microsoft.com/es-es/dotnet/visual-basic/programming-guide/concepts/linq/how-to-query-for-duplicate-files-in-a-directory-tree-linq#feedback)
* Content Source: [docs/visual-basic/programming-guide/concepts/linq/how-to-query-for-duplicate-files-in-a-directory-tree-linq.md](https://github.com/dotnet/docs.es-es/blob/live/docs/visual-basic/programming-guide/concepts/linq/how-to-query-for-duplicate-files-in-a-directory-tree-linq.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by srvbpigh** [comment]
Hello, @JKValero
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Issue moved to [dotnet/docs #15827](https://github.com/dotnet/docs/issues/15827) via [**ZenHub**](https://www.zenhub.com/)

**Comment by v-maudel** [comment]
Hola, @JKValero 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/15827. 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
