### ISSUE TITLE
Referencias incorrectas

### ISSUE THREAD

**Issue by Artilaina** [dotnet/docs.es-es#154]
Se han traducido incorrectamente las palabras clave del árbol de temas de LinQ. En el árbol aparece la palabra clave "en" cuando debería ser "in" por un lado y "on" por otro.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8ebf8c1a-b533-5e93-4913-feb709e8b97a
* Version Independent ID: 0ed9b336-f78e-3e3e-b885-953d70c660c8
* Content: [Palabras clave de consulta: Referencia de C#](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/query-keywords#feedback)
* Content Source: [docs/csharp/language-reference/keywords/query-keywords.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/language-reference/keywords/query-keywords.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @Artilaina
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hola, @Artilaina:   

Gracias por sus comentarios.  

El equipo lingüístico ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/query-keywords#feedback.   

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios.  

Atentamente,  
Equipo internacional de Microsoft Docs
