### ISSUE TITLE
Readonly en propiedades

### ISSUE THREAD

**Issue by EM15** [dotnet/docs.es-es#155]
Estoy utilizando C# 8.0 y el modificar 'readonly' no me funciona en las propiedades según los ejemplos de: "Ejemplos de modificadores de solo lectura"

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 26899b81-d6f9-534a-83ee-283dd8aae545
* Version Independent ID: 3061125d-7de4-97ef-ccb0-ee792d6f2ae1
* Content: [readonly (palabra clave) - Referencia de C#](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/keywords/readonly#readonly-member-examples)
* Content Source: [docs/csharp/language-reference/keywords/readonly.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/language-reference/keywords/readonly.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @EM15
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [dotnet/docs #16758](https://github.com/dotnet/docs/issues/16758) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ticianaciminari** [comment]
Issue moved to [dotnet/docs #16759](https://github.com/dotnet/docs/issues/16759) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hola, @EM15:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/16759.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
