### ISSUE TITLE
Aparente error en segmento de código

### ISSUE THREAD

**Issue by jfcardenas** [dotnet/docs.es-es#156]
En la sección Uso del modelo
    var size = new HouseData() { Size = 2.5F };
    var predEngine = mlContext.CreatePredictionEngine&lt;HouseData, Prediction&gt;(model);
    var price = predEngine.Predict(size);
Creo que la segunda línea debería ser (falta la propiedad Model):
    var predEngine = mlContext.Model.CreatePredictionEngine&lt;HouseData, Prediction&gt;(model);
Puesto que, tal como está produce un error.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [¿Qué es ML.NET y cómo funciona? - ML.NET](https://docs.microsoft.com/es-es/dotnet/machine-learning/how-does-mldotnet-work#feedback)
* Content Source: [docs/machine-learning/how-does-mldotnet-work.md](https://github.com/dotnet/docs.es-es/blob/live/docs/machine-learning/how-does-mldotnet-work.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by srvbpigh** [comment]
Hello, @jfcardenas
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #17446](https://github.com/dotnet/docs/issues/17446) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hola, @jfcardenas:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/17446.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
