### ISSUE TITLE
Conceptos sobre esta página

### ISSUE THREAD

**Issue by hfaalaniz** [dotnet/docs.es-es#157]
Soy programador de la vieja guardia (VB6 y algo de VB.Net) y me costaba mucho C#, he decidido estudiarlo por completo y enfocarme en este lenguaje, esta página me ayudo muchísimo a comprender la sintaxis de C#; deseo hacerles un pedido, continúen con este proyecto, involucren a los que estudian a través de esta página y verán como va a cambiar, direccionenla a programadores como yo, que desean actualizarse pero no tenemos una introducción al lenguaje de manera fácil y sin demasiadas complicaciones, es decir, "dime con le doy arranque, indícame cual es el boton para encender las luces, cual es el freno y acelerador, que yo me encargaré de investigar el resto", este concepto debe estar presente en toda la enseñanza del lenguaje, desde lo mas simple hasta lo mas complejo. Saludos y pueden contar conmigo para lo que ustedes deseen.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 67ff1559-a7c6-9c97-e543-298fbf63f57f
* Version Independent ID: ec7a656b-a94e-7d88-5162-32e931f2e094
* Content: [Colección de datos: tutorial interactivo de introducción a C#](https://docs.microsoft.com/es-es/dotnet/csharp/tutorials/intro-to-csharp/list-collection?tutorial-step=7#feedback)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/list-collection.yml](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/tutorials/intro-to-csharp/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @hfaalaniz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @hfaalaniz 

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
