### ISSUE TITLE
En si cuales son las funciones de los servicios locales ? 

### ISSUE THREAD

**Issue by DragonLord17** [dotnet/docs.es-es#166]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ac412e65-fc71-0072-ba33-e532be0e94b5
* Version Independent ID: 5b7e0817-b120-8a45-054f-6f13161dbbf8
* Content: [Desarrollar aplicaciones de servicios de Windows](https://docs.microsoft.com/es-es/dotnet/framework/windows-services/)
* Content Source: [docs/framework/windows-services/index.md](https://github.com/dotnet/docs.es-es/blob/live/docs/framework/windows-services/index.md)
* Product: **dotnet-framework**
* GitHub Login: @ghogen
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #18667](https://github.com/dotnet/docs/issues/18667) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hola, @DragonLord17:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/18667.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
