### ISSUE TITLE
checksumalgorithm

### ISSUE THREAD

**Issue by jams6** [dotnet/docs.es-es#167]
Hay incongruencias en estas 2 categorías, por ejemplo:

En la categoría 
Opciones del compilador de C#, por categoría - checksumalgorithm:<alg>
Dice que el valor predeterminado es SHA1 (predeterminado) 

Pero en la categoría 
Opciones del compilador de C#, por orden alfabético - -checksumalgorithm:<alg>
Dice que el valor predeterminado es SHA256 (valor predeterminado) 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8a3026d8-a871-b6a5-04dd-393212fdf331
* Version Independent ID: 29b22a16-f7dd-9c66-4393-2a8ea09b3ae8
* Content: [Opciones del compilador de C#, por categoría](https://docs.microsoft.com/es-es/dotnet/csharp/language-reference/compiler-options/listed-by-category)
* Content Source: [docs/csharp/language-reference/compiler-options/listed-by-category.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/language-reference/compiler-options/listed-by-category.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @jams6
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @<nombre del colaborador de GITHUB>:

Valoramos enormemente su comentario y estamos haciendo todo lo posible por mejorar su experiencia en docs.microsoft.com. No obstante, necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?
La documentación dice:

> Especifique el algoritmo para calcular la suma de comprobación del archivo de origen almacenada en el archivo PDB. Los valores admitidos son: SHA1 (predeterminado) o SHA256.
> Debido a problemas de colisión con SHA1, Microsoft recomienda SHA256.

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by jams6** [comment]
Cuando cambias de pagina a:
Opciones del compilador de C#, por orden alfabético
ahora dice que el predeterminado es SHA256 (valor predeterminado) y no SHA1.

-checksumalgorithm:<alg>	
Especifica el algoritmo para calcular la suma de comprobación del archivo de origen almacenada en el archivo PDB. Los valores admitidos son: SHA256 (valor predeterminado) o SHA1.
Debido a problemas de colisión con SHA1, Microsoft recomienda SHA256.

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #18925](https://github.com/dotnet/docs/issues/18925) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hola, @jams6:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/18925.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
