### ISSUE TITLE
Documents are written in formal tone

### ISSUE THREAD

**Issue by jamolina** [dotnet/docs.es-es#43]
While reading your [Voice and tone guidelines](https://github.com/dotnet/docs/blob/master/styleguide/voice-tone.md) I see that you want the documentation to be more conversational. But, when reading the documentation in Spanish, I noticed you guys are using a more formal tone because of the use of the formal conjugations for the second person (For more context, you can read about the [five ways of saying You in Spanish](https://www.spanishdict.com/guide/you-in-spanish)).

This was probably because of the way the translator works by default. I don't know if the Spanish translator you use, has an option to change this default behavior and use the informal "you" conjugations. Otherwise, I would like to start contributing to try to improve the readability of the Spanish conjugations. But, I wanted to start this conversation before actually doing it, so I can confirm this is the one you want to go.

It is also important to mention, that this informal tone is widely used in Mexico. But, I am not sure whether other countries use the more formal tone on a regular basis

**Comment by CeciAc** [comment]
Hello, @jamolina 
 
Thank you for your feedback.
 
Our linguistic team is reviewing your suggestions . We'll let you know of the resolution.

Kind regards,
Microsoft DOCS International Team

**Comment by gosali** [comment]
@jamolina,

Could you please provide us with examples articles within Dotnet where this tone was used?  

Thank you a lot.

Kind regards,
Microsoft DOCS International Team

**Comment by jamolina** [comment]
Of course, here is an example:
https://docs.microsoft.com/es-es/dotnet/core/tutorials/using-on-windows-full-solution

> Llame "Library" al proyecto y "Golden" a la solución. Deje desactivada la casilla Crear directorio para la solución. Haga clic en Aceptar.

Based on your Voice and tone guidelines, I would think it should read something like:

> *Nombra* "Library" al proyecto y "Golden" a la solución. *Deja* desactivada la casilla Crear directorio para la solución. *Haz* clic en Aceptar.

Small details, but the tone is more friendly.

**Comment by CESARDELATORRE** [comment]
I agree on those suggestions when talking Spanish from Spain. (es-es)

Estoy de acuerdo con estas sugerencias para Español de España. (es-es) 

Gracias, :)

**Comment by CeciAc** [comment]
Hi @jamolina @CESARDELATORRE 
We assigned this issue to our Spanish Language Moderator. Please check their comments below:
---
This is an issue that has been studied carefully by MS. It is true that in Spain the use of "tu" is more conversational, but as these texts are written also for Latinomerican countries we should take into account the use of "tu" in those countries. For instance, in some countries it is really informal: a person would use "tu" with her children, but would use "usted" with his/her parents and spouse.
In other countries, where they use "vos", "tu" is not used at all. 
Therefore, it was decided to use "usted" as it is known and used in all countries.

Regarding to "nombrar", it is different from "llamar" or "asignar un nombre a algo" according to the RAE.
---
Thanks again for your feedback.
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team
