### ISSUE TITLE
Problems with the program

### ISSUE THREAD

**Issue by Alejaime** [dotnet/docs.es-es#49]
Why does the message "Program.cs (10,31) appear: error CS1056: Character 'unexpected' $" when compiling with "C: \ Windows \ Microsoft.NET \ Framework64 \ v4.0.30319 \ csc"?
and when I remove the "$" character the messages "Program.cs (9,31) appear: error CS0246: Can not find the type or name of the namespace 'BankAccount' (missing a directive using or a
 assembly reference?)
Program.cs (22,42): error CS0246: Can not find the type or namespace name 'BankAccount' (missing a using directive or a
 Assembly reference?) "

How do I correct it?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 24c8353f-69e7-9068-9b18-df0198a1b122
* Version Independent ID: 823031fe-c8a4-69cd-2b1a-9faacd282aab
* Content: [Introducción al tutorial de clases: inicios rápidos para entornos locales de C#](https://docs.microsoft.com/es-es/dotnet/csharp/quick-starts/introduction-to-classes)
* Content Source: [docs/csharp/quick-starts/introduction-to-classes.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/quick-starts/introduction-to-classes.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hello, @Alejaime , 
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team

**Comment by ibecerra** [comment]
Revisa el "namespace classes", debe ser igual en ambos archivos (programs.cs y CuentaBancaria.cs)

**Comment by sevega** [comment]
ibecerra, gracias por brindar tu comentario. Tuve un problema similar al de LisandroSu y me al ver tu comentario revise mis documentos, corregí y con eso pude complar mi programa.
Nuevamente gracias
