### ISSUE TITLE
Entity Framework

### ISSUE THREAD

**Issue by alexitokim** [dotnet/docs.es-es#50]
¿como puedo trabajar con Entity Framework en Windows Forms y C# con la arquitectura de programción en Capas?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 3adba90a-e351-7149-1e42-50be9d83e76a
* Version Independent ID: 24841c60-4bdb-d1cd-a5a6-32ae24a503ac
* Content: [Referencia del lenguaje Entity SQL](https://docs.microsoft.com/es-es/dotnet/framework/data/adonet/ef/language-reference/)
* Content Source: [docs/framework/data/adonet/ef/language-reference/index.md](https://github.com/dotnet/docs.es-es/blob/live/docs/framework/data/adonet/ef/language-reference/index.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hola, @alexitokim: 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
