### ISSUE TITLE
La dirección de UploadFile necesita incluir un nombre de archivo. Al cargar archivos con el método UploadFile , debe proporcionar un nombre de archivo en la ruta de acceso de destino.

### ISSUE THREAD

**Issue by yapusito** [dotnet/docs.es-es#52]
Esa respuesta la hizo el mismo de: el teclado dejó de funcionar, presione una tecla para continuar"

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b160765f-ed50-e0a8-a0b5-0295f91e8463
* Version Independent ID: 44084b0a-77b8-5e12-a602-84a55ef1f5a0
* Content: [La dirección de UploadFile necesita incluir un nombre de archivo.](https://docs.microsoft.com/es-es/dotnet/visual-basic/misc/the-address-for-uploadfile-needs-to-include-a-filename)
* Content Source: [docs/visual-basic/misc/the-address-for-uploadfile-needs-to-include-a-filename.md](https://github.com/dotnet/docs.es-es/blob/live/docs/visual-basic/misc/the-address-for-uploadfile-needs-to-include-a-filename.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by gosali** [comment]
Issue moved to [dotnet/docs #7135](https://github.com/dotnet/docs/issues/7135) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gosali** [comment]
Hola, @yapusito :  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/dotnet/docs/issues/7135.  

Apreciamos su contribución a nuestros artículos.    

Atentamente,  
Equipo internacional de Microsoft Docs
