### ISSUE TITLE
Bad Prediction

### ISSUE THREAD

**Issue by JonathanLoscalzo** [dotnet/docs.es-es#53]
With this data, my predictions were "Positive" both. :-(

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: c8e22825-c4ee-5a36-f911-8ad456970ecc
* Version Independent ID: ad0bf640-7dfc-1184-077c-358bb14277a7
* Content: [Uso de ML.NET en un escenario de clasificación binaria de análisis de sentimiento](https://docs.microsoft.com/es-es/dotnet/machine-learning/tutorials/sentiment-analysis)
* Content Source: [docs/machine-learning/tutorials/sentiment-analysis.md](https://github.com/dotnet/docs.es-es/blob/live/docs/machine-learning/tutorials/sentiment-analysis.md)
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Seems to be the same issue reported at 
https://github.com/dotnet/docs/issues/7024. Closing as duplicate.
