### ISSUE TITLE
The final steeps to fix the issue

### ISSUE THREAD

**Issue by oranteso** [dotnet/docs.es-es#54]
Go to HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU and set “UseWUServer” to 0 (DoNotUseWUServer.reg)
restart computer
Install .NET Framework 3.5 (ex. go to ‘Windows Features’, select ‘.NET Framework 3.5…’ and press OK)
Go to HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU and set “UseWUServer” to 1 (UseWUServer.reg)
restart computer

Enjoy

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: ea654e23-2ec5-637e-99c3-8870b895030c
* Version Independent ID: 9c054590-c5e3-199c-b852-e1a856b4aae7
* Content: [Instalación de .NET Framework 3.5 en Windows 10, Windows 8.1 y Windows 8](https://docs.microsoft.com/es-es/dotnet/framework/install/dotnet-35-windows-10)
* Content Source: [docs/framework/install/dotnet-35-windows-10.md](https://github.com/dotnet/docs.es-es/blob/live/docs/framework/install/dotnet-35-windows-10.md)
* GitHub Login: @rlander
* Microsoft Alias: **mairaw**

**Comment by LisandroSu** [comment]
Hello, @oranteso 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
