### ISSUE TITLE
Wrong examples

### ISSUE THREAD

**Issue by jssprt** [dotnet/docs.es-es#60]
You need to re-work many examples localised into Spanish of this page:
https://docs.microsoft.com/es-es/dotnet/standard/base-types/regular-expression-language-quick-reference
For example, the regex:
th(e|is|at)
doesn’t match:
"el", "este" en "este es el día. "
Whether a human translator revise the examples or just don’t machine-translate them.
Best regards,

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 16d4698e-4220-c422-a554-8a481803d240
* Version Independent ID: f0e3b82a-8d81-ad9e-97fc-efb92f7d0d38
* Content: [Lenguaje de expresiones regulares - Referencia rápida](https://docs.microsoft.com/es-es/dotnet/standard/base-types/regular-expression-language-quick-reference)
* Content Source: [docs/standard/base-types/regular-expression-language-quick-reference.md](https://github.com/dotnet/docs.es-es/blob/live/docs/standard/base-types/regular-expression-language-quick-reference.md)
* Product: **dotnet**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
Hello, @jssprt 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jssprt,  

Thank you for your feedback. 
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/es-es/dotnet/standard/base-types/regular-expression-language-quick-reference.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 


Kind regards, 
Microsoft DOCS International Team
