### ISSUE TITLE
Vínculo roto

### ISSUE THREAD

**Issue by eugeniomiro** [dotnet/docs.es-es#61]
El vínculo a Esquema de la configuración de red Network Settings Schema está roto, devuelve 404.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 48ca1037-b898-cfa6-6e79-c20fe882886a
* Version Independent ID: 59e24545-1918-6b36-4139-7422e95a7940
* Content: [HttpWebRequestElement Class (System.Net.Configuration)](https://docs.microsoft.com/es-es/dotnet/api/system.net.configuration.httpwebrequestelement?view=netframework-4.7.2)
* Content Source: [xml/System.Net.Configuration/HttpWebRequestElement.xml](https://github.com/dotnet/dotnet-api-docs.es-es/blob/live/xml/System.Net.Configuration/HttpWebRequestElement.xml)
* Product: **.net**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by LisandroSu** [comment]
Hola, @eugeniomiro : 

Gracias por sus comentarios. 

Los revisaremos y nos pondremos en contacto con usted lo antes posible. 

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by CeciAc** [comment]
Gracias por sus comentarios. 

El equipo de ingeniería ha revisado las sugerencias y las ha aceptado. Hemos implementado sus comentarios y los hemos publicado en los artículos actualizados del sitio de Docs en las siguientes páginas: https://docs.microsoft.com/es-es/dotnet/api/system.net.configuration.httpwebrequestelement?view=netframework-4.7.2.  

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios. 

Atentamente, 

Equipo internacional de Microsoft Docs
