### ISSUE TITLE
Aprendiendo es mas facil

### ISSUE THREAD

**Issue by atzellm** [dotnet/docs.es-es#64]
Hola la  verdad llevaba días buscando cursos sobre programacion con C#, mi ingles no es muy bueno y se me dificulta encontrar buenos cursos. Pero la verdad estas expliaciones por parte de Microsoft son muy buenas cortas y bien redactadas estoy aprendiendo mejor de lo que esperaba, Gracias por todo. 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8b514dfb-f00b-8ac3-4027-7a28770f959e
* Version Independent ID: 7db3af08-9406-10da-76a1-1f8db30d1d2d
* Content: [Tutorial interactivo Hola mundo: guías de inicio rápido de C#](https://docs.microsoft.com/es-es/dotnet/csharp/quick-starts/hello-world?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/hello-world.yml](https://github.com/dotnet/docs.es-es/blob/live-sxs/docs/csharp/quick-starts/hello-world.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Hola, @atzellm : 

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
