### ISSUE TITLE
Seguimos con el curso

### ISSUE THREAD

**Issue by atzellm** [dotnet/docs.es-es#65]
De nuevo yo para comentarles que las explicaciones siguen siendo muy buenas y claras, espero poder continuar estudiando el curso y aprendiendo. 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 38072238-34db-51bc-4896-043025bb47b6
* Version Independent ID: d44c00dd-a582-7284-e033-2725cff8123b
* Content: [Tutorial interactivo sobre números en C#: guías de inicio rápido de C#](https://docs.microsoft.com/es-es/dotnet/csharp/quick-starts/numbers-in-csharp?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/numbers-in-csharp.yml](https://github.com/dotnet/docs.es-es/blob/live-sxs/docs/csharp/quick-starts/numbers-in-csharp.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hola, @atzellm: 

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
