### ISSUE TITLE
Un poco mas confuso

### ISSUE THREAD

**Issue by atzellm** [dotnet/docs.es-es#66]
La ultima lección es un poco mas confusa que todas las demas, tal vez un poco mas de explicacion seria genial. 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: f6c237cc-f595-dc78-f09a-fd1c688fe3e2
* Version Independent ID: 0d74beea-afdb-89d3-9d86-54cbdd37d977
* Content: [Tutorial interactivo de interpolación de cadenas: guías de inicio rápido de C#](https://docs.microsoft.com/es-es/dotnet/csharp/quick-starts/interpolated-strings?tutorial-step=5)
* Content Source: [docs/csharp/quick-starts/interpolated-strings.yml](https://github.com/dotnet/docs.es-es/blob/live-sxs/docs/csharp/quick-starts/interpolated-strings.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hola, @atzellm:

Valoramos enormemente su comentario y estamos haciendo todo lo posible por mejorar su experiencia en docs.microsoft.com. No obstante, necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by CeciAc** [comment]
Hola, @atzellm:

Esta es una continuación de nuestro comentario anterior. Necesitamos más información para poder encargarnos de sus comentarios. ¿Puede proporcionar información más detallada y aclarar el comentario?

Atentamente,
Equipo internacional de Microsoft DOCS

**Comment by CeciAc** [comment]
Hola, @atzellm 

Gracias nuevamente por su comentario.

Lamentablemente, aún nos falta información y no podemos procesar sus comentarios. En este momento, cerraremos este problema de GitHub, pero le animamos a enviar más comentarios en el futuro.

Atentamente,
Equipo internacional de Microsoft DOCS
