### ISSUE TITLE
Muy buen compilador el del navegador

### ISSUE THREAD

**Issue by punisher97** [dotnet/docs.es-es#67]
Tutoriales básicos pero importantes, gracias

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 0d9e98de-9df3-d63f-f6a6-aa079eb5095f
* Version Independent ID: a057574c-020f-a9f0-9dfc-f8936a1132fe
* Content: [Tutorial interactivo sobre colecciones: guías de inicio rápido de C#](https://docs.microsoft.com/es-es/dotnet/csharp/quick-starts/list-collection?tutorial-step=7)
* Content Source: [docs/csharp/quick-starts/list-collection.yml](https://github.com/dotnet/docs.es-es/blob/live-sxs/docs/csharp/quick-starts/list-collection.yml)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hola, @punisher97: 

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
