### ISSUE TITLE
Settings ambiguo. Solución a este problema.

### ISSUE THREAD

**Issue by JKValero** [dotnet/docs.es-es#72]
Hola amigos: 
Tengo el siguiente error: My.Settings.Nube	'Settings' es ambiguo entre las declaraciones de los módulos 'My.MySettingsProperty' y 'My.MySettingsProperty'.	

Este es un error "muy" común en las aplicaciones de Windows Forms. La ayuda que aparece es muy concisa y no aporta nada a la solución. 
Sería bueno poder efectuar una ayuda con mayor detalle a las diferentes causas de este problema porque en los Foros no hay ayuda disponible que destrabe este problema. Por ejemplo, en mi aplicación no se encuentra el archivo duplicado, y por ende, no sirve la ayuda de la nube.
Gracias

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a01e1bb8-1028-a18c-5b32-6c1d5c930fad
* Version Independent ID: b7f22c79-13c8-cf3c-aadf-cb8120894eb5
* Content: ['&lt;nombre&gt; ' es ambiguo entre las declaraciones de módulos ' &lt;nombredemódulo1&gt; ' y ' &lt;nombredemódulo2&gt;'](https://docs.microsoft.com/es-es/dotnet/visual-basic/misc/bc30562)
* Content Source: [docs/visual-basic/misc/bc30562.md](https://github.com/dotnet/docs.es-es/blob/live/docs/visual-basic/misc/bc30562.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by CeciAc** [comment]
Hola, @JKValero 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
