### ISSUE TITLE
Error al correr aplicación

### ISSUE THREAD

**Issue by SASFMONTOYA** [dotnet/docs.es-es#73]
Al correr la aplicación (Windows Form - Framework 4.5) me aparece el error « System.Runtime.InteropServices.ExternalException: 'Error genérico en GDI+.' » en la línea de código «bmp1.Save(@"c:\TestPhotoQualityFifty.jpg", jpgEncoder, myEncoderParameters);»

![image](https://user-images.githubusercontent.com/22794697/48809764-fbc50000-ecf3-11e8-8bdc-85d230da73cb.png)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: c64c2ca1-85a8-8bfc-83f9-9952e4471b2b
* Version Independent ID: 19482e28-e073-8bd2-5e97-9e2477a4568a
* Content: [Cómo: Establecer el nivel de compresión de imágenes JPEG](https://docs.microsoft.com/es-es/dotnet/framework/winforms/advanced/how-to-set-jpeg-compression-level)
* Content Source: [docs/framework/winforms/advanced/how-to-set-jpeg-compression-level.md](https://github.com/dotnet/docs.es-es/blob/live/docs/framework/winforms/advanced/how-to-set-jpeg-compression-level.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hola, @SASFMONTOYA 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs

**Comment by SASFMONTOYA** [comment]
> Hola, @SASFMONTOYA
> 
> Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 
> 
> Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 
> 
> Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 
> 
> Apreciamos su contribución a nuestros artículos.  
> 
> Atentamente, 
> Equipo internacional de Microsoft Docs

Okey, mil gracias, perdón la confusión.
