### ISSUE TITLE
traducción al castellano un poco tipo "india"

### ISSUE THREAD

**Issue by dhernandezb** [dotnet/docs.es-es#74]
Falta corregir la traducción automática que se hace al castellano desde el ingles.
Muchas veces hay que leer la frase original en ingles para saber que quiere decir.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 72eaf9f8-fd58-769f-3f8e-41797c4c3a75
* Version Independent ID: 71d14c6d-e4f7-5de7-f317-d178af9a1b95
* Content: [Cómo: Forzar un argumento para que pase como un valor (Visual Basic)](https://docs.microsoft.com/es-es/dotnet/visual-basic/programming-guide/language-features/procedures/how-to-force-an-argument-to-be-passed-by-value)
* Content Source: [docs/visual-basic/programming-guide/language-features/procedures/how-to-force-an-argument-to-be-passed-by-value.md](https://github.com/dotnet/docs.es-es/blob/live/docs/visual-basic/programming-guide/language-features/procedures/how-to-force-an-argument-to-be-passed-by-value.md)
* Product: **dotnet-visualbasic**
* GitHub Login: @KathleenDollard
* Microsoft Alias: **kdollard**

**Comment by CeciAc** [comment]
Hola, @dhernandezb 

Gracias por sus comentarios. La página en cuestión se ha traducido automáticamente. Con este método la traducción no siempre es totalmente comprensible. Recientemente hemos agregado la opción "Leer en inglés" en la parte derecha de la página para que pueda cambiar a la versión en inglés sin tener que cambiar la configuración de idioma. 

Atentamente, 
Equipo internacional de Microsoft Docs
