### ISSUE TITLE
Gracias

### ISSUE THREAD

**Issue by mps007** [dotnet/docs.es-es#81]
Todos Los tutoriales estan muey bien explicados.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: fb6905a9-e9ec-df6f-5733-dfb25a41b97a
* Version Independent ID: fe0e2716-651b-a883-6371-ded1ace94a11
* Content: [Números en C#: tutorial de introducción a C#](https://docs.microsoft.com/es-es/dotnet/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local)
* Content Source: [docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local.md](https://github.com/dotnet/docs.es-es/blob/live/docs/csharp/tutorials/intro-to-csharp/numbers-in-csharp-local.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hola, @mps007 

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas. 

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia. 

Atentamente, 
Equipo internacional de Microsoft Docs
