### ISSUE TITLE
Traducción automática

### ISSUE THREAD

**Issue by manolomaroto** [dotnet/docs.es-es#96]
La traducción automática es una basura. Traduce palabra por palabra y se pierde el sentido de la oración.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: d3850222-3c85-c851-006b-5236b41608d1
* Version Independent ID: a7734cb0-e62c-b9b5-961f-f757f8450967
* Content: [Tipos de las colecciones Hashtable y Dictionary](https://docs.microsoft.com/es-es/dotnet/standard/collections/hashtable-and-dictionary-collection-types)
* Content Source: [docs/standard/collections/hashtable-and-dictionary-collection-types.md](https://github.com/dotnet/docs.es-es/blob/live/docs/standard/collections/hashtable-and-dictionary-collection-types.md)
* Product: **dotnet**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by CeciAc** [comment]
Hola, @manolomaroto 

Gracias por sus comentarios. La página en cuestión se ha traducido automáticamente. Con este método la traducción no siempre es totalmente comprensible. Recientemente hemos agregado la opción "Leer en inglés" en la parte derecha de la página para que pueda cambiar a la versión en inglés sin tener que cambiar la configuración de idioma. 

Atentamente, 
Equipo internacional de Microsoft Docs
